name: test-unit

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [7.4]
        dependency-version: [prefer-lowest, prefer-stable]

    name: Test PHP${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, json, mbstring, xdebug
          coverage: none

      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Test and Coverage
        run: |
          mkdir -p coverage
          cp phpunit.xml.dist phpunit.xml
          ./vendor/bin/phpunit --coverage-clover=coverage/coverage.xml
          echo "项目文件列表："
          ls -R .
          echo "coverage 文件列表："
          ls -R coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          format: clover
          file: coverage/coverage.xml

#          ./vendor/bin/phpunit --configuration=phpunit.xml

#      - name: Test and Coverage
#        run: cp phpunit.xml.dist phpunit.xml && composer test:unit
#
#      - name: Coveralls
#        uses: coverallsapp/github-action@v2
#        with:
#          format: clover
#          file: ${{ github.workspace }}/coverage.xml
